Added Cross-Platform Compatibility
kozmer/log4j-shell-poc pull request #20
Opened 2021-12-16 05:06 UTC by Dannygop

Changes poc.py:
- Added: a bit more error handling
- Added: cross platform compatibility for shell
- Cleaned up code to be a bit more consistent

2021-12-16 09:09 UTC, z9fr commented
hi please resolved conflicts

2021-12-16 09:16 UTC, Dannygop commented
Should be fixed now

2021-12-16 11:25 UTC, kozmer commented
I don't currently have anywhere to test the Windows compatibility, is it okay if you make a PoC video w/ Windows and show me? Thank you :)

2021-12-16 15:05 UTC, svmorris commented
Hi,
Yea sorry for getting back a bit late on this. I have 2 problems which are really slowing down this review process:
1: You have changed the file in many places, most of them not relevant to the purpose of the patch. ie things like this:
![Screenshot from 2021-12-16 16-03-27](https://user-images.githubusercontent.com/46561460/146396155-b00a53c9-0b48-4ae0-9082-510e9171ba3e.png)

2. This is more of a fault of my own, but I don't have a windows computer with me, and we are waiting on @kozmer  to be free so he can test it.

2021-12-16 16:04 UTC, LennardTFD requested changes

2021-12-16 16:04 UTC, LennardTFD commented on poc.py
> +    print(Fore.GREEN + f"[+] Starting the Web server on port {webport} http://0.0.0.0:{webport}", end="\n\n")
Due to change of parameter names (even though they are pretty inconsistent):

https://github.dev/Dannygop/log4j-shell-poc/blob/7f5d0bd7400f64cc4a4e1abc89e2d73eb8113a89/poc.py#L97 `webport` needs to be changed to `web_port` twice.

2021-12-16 17:18 UTC, Dannygop commented on poc.py
> +    print(Fore.GREEN + f"[+] Starting the Web server on port {webport} http://0.0.0.0:{webport}", end="\n\n")
ahh yes, completely overlooked that because I was just changing it on github and not in my ide.

Thank you for noticing

2021-12-16 17:22 UTC, kozmer reviewed
All works fine on my end, thanks :)

2021-12-16 17:22 UTC, merged

2021-12-16 17:22 UTC, Dannygop commented
I'm sorry, the reason for all those small changes are, because I use PyCharm as IDE and it gives: spelling checks, syntax corrections and indentation corrections.
I pressed reformat file to apply those changes.

2021-12-16 17:43 UTC, z9fr commented
its all good we already fixed it :smiley: I think the java class you added gives a IllegalThreadStateException but the exploit still works on windows and unix 

```
java.lang.IllegalThreadStateException: process hasn't exited
        at java.lang.UNIXProcess.exitValue(UNIXProcess.java:289)
        at Exploit.<init>(Exploit.java:31)
        at Exploit.main(Exploit.java:9)
```

2021-12-17 14:23 UTC, Dannygop commented
> its all good we already fixed it 😃 I think the java class you added gives a IllegalThreadStateException but the exploit still works on windows and unix
> 
> ```
> java.lang.IllegalThreadStateException: process hasn't exited
>         at java.lang.UNIXProcess.exitValue(UNIXProcess.java:289)
>         at Exploit.<init>(Exploit.java:31)
>         at Exploit.main(Exploit.java:9)
> ```

Where does it gives this? I only added another function which checks the OS name and returns a string back (sorry for the late reply)

2021-12-17 15:07 UTC, kozmer commented
> > its all good we already fixed it smiley I think the java class you added gives a IllegalThreadStateException but the exploit still works on windows and unix
> > ```
> > java.lang.IllegalThreadStateException: process hasn't exited
> >         at java.lang.UNIXProcess.exitValue(UNIXProcess.java:289)
> >         at Exploit.<init>(Exploit.java:31)
> >         at Exploit.main(Exploit.java:9)
> > ```
> 
> Where does it gives this? I only added another function which checks the OS name and returns a string back (sorry for the late reply)
> 
> Btw, was it intentional to revert the code to the old state?

Yeah, we reverted back a few commits. Seems like the new exploit was causing issues within the Docker container when running the exploit. It didn't necessarily break things but it was making things quite unstable on my end which I noticed. Feel free to make another PR but could you test it/make a PoC of it working on Windows if you do? Thanks!